version: "3.8"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      MSSQL_SA_PASSWORD: "mssqlS4p4ssw02d"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./db:/var/opt/mssql

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
